name: GMT CRANES
on:
   push:
    branches: -main
jobs:
  web-deploy:
    name: 🎉 GMT-CRANES
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        ftp-username:  ${{ secrets.FTP_USERNAME }}